let musicList = [
    {
        id: 1,
        name: "Snowman",
        artist: "Sia",
        src: "SiaEverydayIsChristmas",
        lyric: [
           'Don\'t cry, snowman, not in front of me',
'Who\'ll catch your tears if you can\'t catch me, darling?',
'If you can\'t catch me, darling',
'Don\'t cry, snowman, don\'t leave me this way',
'A puddle of water can\'t hold me close, baby',
'Can\'t hold me close, baby',
'',
'I want you to know that I\'m never leaving',
'\'Cause I\'m Mrs. Snow. \'Til death we\'ll be freezing',
'Yeah, you are my home, my home for all seasons',
'So, come on, let\'s go',
'',
'Let\'s go below zero',
'And hide from the sun',
'I\'ll love you forever',
'Where we\'ll have some fun',
'Yes, let\'s hit the North Pole',
'And live happily',
'Please, don\'t cry no tears now',
'It\'s Christmas, baby',
'',
'My snowman and me, yeah',
'My snowman and me',
'Baby',
'',
'Don\'t cry, snowman, don\'t you fear the sun',
'Who\'ll carry me without legs to run, honey?',
'Without legs to run, honey',
'Don\'t cry, snowman, don\'t you shed a tear',
'Who\'ll hear my secrets if you don\'t have ears, baby?',
'If you don\'t have ears, baby',
'',
'I want you to know that I\'m never leaving',
'\'Cause I\'m Mrs. Snow. \'Til death we\'ll be freezing',
'Yeah, you are my home, my home for all seasons',
'So, come on, let\'s go',
'',
'Let\'s go below zero',
'And hide from the sun',
'I\'ll love you forever',
'Where we\'ll have some fun',
'Yes, let\'s hit the North Pole',
'And live happily',
'Please, don\'t cry no tears now',
'It\'s Christmas, baby',
'',
'My snowman and me, yeah',
'My snowman and me',
'Baby',
],
    },
    {
        id: 2,
        name: "APT.",
        artist: "ROSÉ and Bruno Mars",
        src: "Apt",
        lyric: [
            
'Chaeyeongiya joaneun',
'Raendeom geim',
'Raendeom geim',
'Game start',
'',
'Apateu, apateu',
'Apateu, apateu',
'Apateu, apateu',
'Uh, uh-huh, uh-huh',
'Apateu, apateu',
'Apateu, apateu',
'Apateu, apateu',
'Uh, uh-huh, uh-huh',
'',
'Kissy face, kissy face',
'Sent to your phone, but',
'I\'m tryna kiss your lips for real (Uh-huh, uh-huh)',
'Red hearts, red hearts',
'That\'s what I\'m on, yeah',
'Come give me somethin\' I can feel, oh-oh-oh',
'',
'Don\'t you want me like I want you, baby?',
'Don\'t you need me like I need you now?',
'Sleep tomorrow, but tonight, go crazy',
'All you gotta do is just meet me at the',
'',
'Apateu, apateu',
'Apateu, apateu',
'Apateu, apateu',
'Uh, uh-huh, uh-huh',
'Apateu, apateu',
'Apateu, apateu',
'Apateu, apateu',
'Uh, uh-huh, uh-huh',
'',
'It\'s whatever (Whatever), it\'s whatever (Whatever)',
'It\'s whatever (Whatever) you like (Woo)',
'Turn this apateu into a club (Uh-huh, uh-huh)',
'I\'m talkin\' drink, dance, smoke, freak, party all night (Come on)',
'Geonbae, geonbae, girl, what\'s up? Oh-oh-oh',
'',
'Don\'t you want me like I want you, baby?',
'Don\'t you need me like I need you now?',
'Sleep tomorrow, but tonight, go crazy',
'All you gotta do is just meet me at the',
'',
'Apateu, apateu',
'Apateu, apateu',
'Apateu, apateu',
'Uh, uh-huh, uh-huh',
'Apateu, apateu',
'Apateu, apateu',
'Apateu, apateu',
'Uh, uh-huh, uh-huh',
'',
'Hey, so now you know the game',
'Are you ready? \'Cause I\'m comin\' to get ya, get ya, get ya',
'Hold on, hold on',
'I\'m on my way',
'Yeah, yeah, yeah-yeah, yeah',
'I\'m on my way',
'Hold on, hold on',
'I\'m on my way',
'Yeah, yeah, yeah-yeah, yeah',
'I\'m on my way',
'',
'Don\'t you want me like I want you, baby?',
'Don\'t you need me like I need you now?',
'Sleep tomorrow, but tonight, go crazy',
'All you gotta do is just meet me at the',
'',
'Apateu, apateu',
'Apateu, apateu',
'Apateu, apateu',
'Just meet me at the (Uh-huh, uh-huh)',
'Apateu, apateu',
'Apateu, apateu',
'Apateu, apateu',
'Just meet me at the (Uh-huh, uh-huh)',
'Apateu, apateu',
'Apateu, apateu',
'Apateu, apateu',
'Just meet me at the (Uh-huh, uh-huh)',
'Apateu, apateu',
'Apateu, apateu',
'Apateu, apateu',
'Uh, uh-huh, uh-huh'
        ],
    },
    {
        id: 3,
        name: "Baby",
        artist: "Justin Bieber,Ludacris",
        src: "Baby",
        lyric: [
            'Oh, woah',
'Oh, woah',
'Oh, woah',
'You know you love me, I know you care',
'Just shout whenever and I\'ll be there',
'You are my love, you are my heart',
'And we will never, ever, ever be apart',
'Are we an item? Girl, quit playing',
'We\'re just friends, what are you saying?',
'Said, "There\'s another" and looked right in my eyes',
'My first love broke my heart for the first time',
'And I was like',
'Baby, baby, baby, oh',
'Like baby, baby, baby, no',
'Like baby, baby, baby, oh',
'I thought you\'d always be mine, mine',
'Baby, baby, baby, oh',
'Like baby, baby, baby, no',
'Like baby, baby, baby, oh',
'I thought you\'d always be mine, mine',
'Oh, woah',
'Oh, woah',
'Oh, woah',
'For you, I would have done whatever',
'And I just can\'t believe we ain\'t together',
'And I wanna play it cool, but I\'m losin\' you',
'I\'ll buy you anything, I\'ll buy you any ring',
'And I\'m in pieces, baby, fix me',
'And just shake me \'til you wake me from this bad dream',
'I\'m going down, down, down, down',
'And I just can\'t believe my first love won\'t be around',
'And I\'m like',
'Baby, baby, baby, oh',
'Like baby, baby, baby, no',
'Like baby, baby, baby, oh',
'I thought you\'d always be mine, mine',
'Baby, baby, baby, oh',
'Like baby, baby, baby, no',
'Like baby, baby, baby, oh',
'I thought you\'d always be mine, mine',
'Luda!',
'When I was 13, I had my first love',
'There was nobody that compared to my baby',
'And nobody came between us or could ever come above',
'She had me going crazy, oh, I was starstruck',
'She woke me up daily, don\'t need no Starbucks',
'She made my heart pound, and skip a beat when I see her in the street and',
'At school on the playground, but I really wanna see her on the weekend',
'She knows she got me dazing, \'cause she was so amazing',
'And now my heart is breaking, but I just keep on saying',
'Baby, baby, baby, oh',
'Like baby, baby, baby, no',
'Like baby, baby, baby, oh',
'I thought you\'d always be mine, mine',
'Baby, baby, baby, oh',
'Like baby, baby, baby, no',
'Like baby, baby, baby, oh',
'I thought you\'d always be mine, mine',
'I\'m gone',
'Yeah, yeah, yeah',
'Yeah, yeah, yeah',
'Now I\'m all gone',
'Yeah, yeah, yeah',
'Yeah, yeah, yeah',
'Now I\'m all gone',
'Yeah, yeah, yeah',
'Yeah, yeah, yeah',
'Now I\'m all gone',
'Gone, gone, gone, I\'m gone',
        ],
    },
    {
        id: 4,
        name: "Cupid",
        artist: "FIFTY FIFTY",
        src: "Cupid",
        lyric: [
            'La, la, la, la-la-la',
'La, la-la-la, la, la-la-la',
'',
'A hopeless romantic all my life',
'Surrounded by couples all the time',
'I guess I should take it as a sign',
'(Oh why, oh why, oh why, oh why?)',
'',
'I\'m feeling lonely (Lonely)',
'Oh, I wish I\'d find a lover that could hold me (Hold me)',
'Now, I\'m crying in my room',
'So skeptical of love (Say what you say, but I want it more)',
'But still, I want it more, more, more',
'',
'I gave a second chance to Cupid',
'But now, I\'m left here feeling stupid',
'Oh, the way he makes me feel',
'That love isn\'t real',
'Cupid is so dumb',
'',
'I look for his arrows every day',
'I guess he got lost or flew away',
'Waiting around is a waste (Waste)',
'Been counting the days since November',
'Is loving as good as they say?',
'',
'Now I\'m so lonely (Lonely)',
'Oh, I wish I\'d find a lover that could hold me (Hold me)',
'Now I\'m crying in my room',
'So skeptical of love (Say what you say, but I want it more)',
'But still, I want it more, more, more',
'',
'I gave a second chance to Cupid',
'But now, I\'m left here feeling stupid',
'Oh, the way he makes me feel',
'That love isn\'t real',
'Cupid is so dumb',
'(Cupid is so dumb)',
'',
'Hopeless girl is seeking',
'Someone who will share this feeling',
'I\'m a fool',
'A fool for love, a fool for love',
'',
'I gave a second chance to Cupid',
'But now, I\'m left here feeling stupid',
'Oh, the way he makes me feel',
'That love isn\'t real',
'Cupid is so dumb',
'I gave a second chance to Cupid',
'(Hopeless girl is seeking someone)',
'But now, I\'m left here feeling stupid',
'(Who will share this feeling)',
'Oh, the way he makes me feel',
'That love isn\'t real',
'(I\'m a fool)',
'Cupid is so dumb',
'(A fool for love, a fool for love)'
 
        ],
    },
    {
        id: 5,
        name: "Beggin'",
        artist: "Måneskin",
        src: "Beggin",
        lyric: [
           
'Put your loving hand out, baby',
'\'Cause I\'m beggin\'',
'',
'I\'m beggin\', beggin\' you',
'So put your loving hand out, baby',
'I\'m beggin\', beggin\' you',
'So put your loving hand out, darlin\'',
'',
'Riding high when I was king',
'I played it hard and fast, \'cause I had everything',
'I walked away, you won me then',
'But easy come and easy go and it would end',
'',
'So, anytime I bleed, you let me go',
'Yah, anytime I feed, you get me know',
'Anytime I seek, you let me know',
'But I planted that seed, just let me go',
'I\'m on my knees when I\'m beggin\'',
'\'Cause I don\'t wanna lose you',
'Hey, yeah, ra-ta-ta-ta!',
'',
'\'Cause I\'m beggin\', beggin\' you',
'Uh, put your loving hand out, baby',
'I\'m beggin\', beggin\' you, ah',
'And put your loving hand out, darlin\'',
'',
'I need you to understand',
'Tried so hard to be your man',
'The kind of man you want in the end',
'Only then can I begin to live again',
'',
'An empty shell, I used to be',
'The shadow of my life was hangin\' over me',
'A broken man that I don\'t know',
'Won\'t even stand the devil\'s dance to win my soul',
'',
'What we doin\'? What we chasin\'?',
'Why the bottom? Why the basement?',
'Why we got good shit, don\'t embrace it?',
'Why the feel for the need to replace me?',
'You\'re the wrong way track from the good',
'I want to paint a picture tellin\' where we could be at',
'Like a heart in the best way should',
'You can give it away, you had it and you took the pay',
'But I keep walkin\' on, keep openin\' doors',
'Keep hopin\' for, now the door is yours',
'Keep also home',
'\'Cause I don\'t want to live in a broken home, girl, I\'m beggin\'',
'',
'Mmm, yeah-yeah, yeah, I\'m beggin\', beggin\' you',
'So put your loving hand out, baby',
'I\'m beggin\', beggin\' you',
'So put your loving hand out, darlin\'',
'',
'I\'m fighting hard to hold my own',
'Just can\'t make it all alone',
'I\'m holding on, I can\'t fall back',
'I\'m just a calm, \'bout to fade to black',
'',
'I\'m beggin\', beggin\' you',
'Put your loving hand out, baby',
'I\'m beggin\', beggin\' you',
'So put your loving hand out, darlin\'',
'I\'m beggin\', beggin\' you',
'So put your loving hand out, baby',
'I\'m beggin\', beggin\' you',
'So put your loving hand out, darlin\'',
'',
'I\'m beggin\', beggin\' you',
'So put your loving hand out, baby',
'I\'m beggin\', beggin\' you',
'So put your loving hand out'
        ],
    },
    {
        id: 6,
        name: "I Wanna Be Your Slave",
        artist: " Måneskin",
        src: "slave",
        lyric: [
            'I wanna be your slave',
'I wanna be your master',
'I wanna make your heart beat',
'Run like rollercoasters',
'I wanna be a good boy',
'I wanna be a gangster',
'\'Cause you can be the beauty',
'And I could be the monster',
'I love you since this morning',
'Not just for aesthetic',
'I wanna touch your body',
'So fucking electric',
'I know you scared of me',
'You said that I\'m too eccentric',
'I\'m crying all my tears',
'And that\'s fucking pathetic',
'I wanna make you hungry',
'Then I wanna feed ya',
'I wanna paint your face',
'Like you\'re my Mona Lisa',
'I wanna be a champion',
'I wanna be a loser',
'I\'ll even be a clown',
'Cause I just wanna amuse ya',
'I wanna be your sex toy',
'I wanna be your teacher',
'I wanna be your sin',
'I wanna be a preacher',
'I wanna make you love me',
'Then I wanna leave ya',
'\'Cause baby I\'m your David',
'And you\'re my Goliath',
'',
'Because I\'m the devil',
'Who\'s searching for redemption',
'And I\'m a lawyer',
'Who\'s searching for redemption',
'And I\'m a killer',
'Who\'s searching for redemption',
'I\'m a motherfucking monster',
'Who\'s searching for redemption',
'And I\'m a bad guy',
'Who\'s searching for redemption',
'And I\'m a blond girl',
'Who\'s searching for redemption',
'I\'m a freak that',
'Is searching for redemption',
'I\'m a motherfucking monster',
'Who\'s searching for redemption',
'',
'I wanna be your slave',
'I wanna be your master',
'I wanna make your heart beat',
'Run like rollercoasters',
'I wanna be a good boy',
'I wanna be a gangster',
'Cause you can be the beauty',
'And I could be the monster',
'I wanna make you quiet',
'I wanna make you nervous',
'I wanna set you free',
'But I\'m too fucking jealous',
'I wanna pull your strings',
'Like you\'re my telecaster',
'And if you want to use me I could be your puppet',
'',
'\'Cause I\'m the devil',
'Who\'s searching for redemption',
'And I\'m a lawyer',
'Who\'s searching for redemption',
'And I\'m a killer',
'Who\'s searching for redemption',
'I\'m a motherfucking monster',
'Who\'s searching for redemption',
'',
'I wanna be your slave',
'I wanna be your master'
        ],
    },
    {
        id: 7,
        name: "I Wanna Be Yours",
        artist: "Arctic Monkeys",
        src: "Yours",
        lyric: [
           'I wanna be your vacuum cleaner',
'Breathing in your dust',
'I wanna be your Ford Cortina',
'I will never rust',
'If you like your coffee hot',
'Let me be your coffee pot',
'You call the shots, babe',
'I just wanna be yours',
'',
'Secrets I have held in my heart',
'Are harder to hide than I thought',
'Maybe I just wanna be yours',
'I wanna be yours, I wanna be yours',
'Wanna be yours, wanna be yours, wanna be yours',
'',
'Let me be your \'leccy meter and I\'ll never run out',
'Let me be the portable heater that you\'ll get cold without',
'I wanna be your setting lotion (wanna be)',
'Hold your hair in deep devotion (how deep?)',
'At least as deep as the Pacific Ocean',
'I wanna be yours',
'',
'Secrets I have held in my heart',
'Are harder to hide than I thought',
'Maybe I just wanna be yours',
'I wanna be yours, I wanna be yours',
'Wanna be yours, wanna be yours, wanna be yours',
'Wanna be yours, wanna be yours, wanna be yours',
'Wanna be yours, wanna be yours',
'',
'I wanna be your vacuum cleaner (Wanna be yours)',
'Breathing in your dust (Wanna be yours)',
'I wanna be your Ford Cortina (Wanna be yours)',
'I will never rust (Wanna be yours)',
'I just wanna be yours (Wanna be yours)',
'I just wanna be yours (Wanna be yours)',
'I just wanna be yours (Wanna be yours)'
        ],
    },
    {
        id: 8,
        name: "Falling",
        artist: "Trevor Daniel",
        src: "falling",
        lyric: [
           'My last made me feel like I would never try again',
'But when I saw you, I felt something I never felt',
'Come closer, I\'ll give you all my love',
'If you treat me right, baby, I\'ll give you everything',
'My last made me feel like I would never try again',
'But when I saw you, I felt something I never felt',
'Come closer, I\'ll give you all my love',
'If you treat me right, baby, I\'ll give you everything',
'',
'Talk to me, I need to hear you need me like I need ya',
'Fall for me, I wanna know you feel how I feel for you, love',
'Before you, baby, I was numb, drown the pain by pouring up',
'Speeding fast on the run, never want to get caught up',
'Now you the one that I\'m calling',
'Swore that I\'d never forget, don\'t think I\'m just talking',
'I think I might go all in, no exceptions, girl, I need ya',
'',
'Feeling like I\'m out of my mind, cause I can\'t get enough',
'Only one that I give my time, \'cause I got eyes for ya',
'Might make an exception for ya, \'cause I been feeling ya',
'Think I might be out of my mind, I think that you\'re the one',
'',
'My last made me feel like I would never try again',
'But when I saw you, I felt something I never felt',
'Come closer, I\'ll give you all my love',
'If you treat me right, baby, I\'ll give you everything',
'My last made me feel like I would never try again',
'But when I saw you, I felt something I never felt',
'Come closer, I\'ll give you all my love',
'If you treat me right, baby, I\'ll give you everything',
'',
'I\'ll never give my all again',
'\'Cause I\'m sick of falling down',
'When I open up and give my trust',
'They find a way to break it down',
'Tear me up inside, and you break me down'
        ],
    },
    {
        id: 9,
        name: "Señorita",
        artist: "Shawn Mendes,Camila Cabello",
        src: "Señorita",
        lyric: [
           'I love it when you call me Señorita',
'I wish I could pretend I didn\'t need ya',
'But every touch is ooh-la-la-la',
'It\'s true la-la-la',
'Ooh, I should be running',
'Ooh, you keep me coming',
'For ya',
'',
'Land in Miami',
'The air was hot from summer rain',
'Sweat dripping off me',
'Before I even knew her name la-la-la',
'It felt like ooh-la-la-la',
'Yeah, no',
'',
'Sapphire moonlight',
'We danced for hours in the sand',
'Tequila Sunrise',
'Her body fit right in my hands, la-la-la',
'It felt like ooh-la-la-la',
'Yeah',
'',
'I love it when you call me Señorita',
'I wish I could pretend I didn\'t need ya',
'But every touch is ooh-la-la-la',
'It\'s true la-la-la',
'Ooh, I should be running',
'Ooh, you know I love it',
'',
'When you call me Señorita',
'I wish it wasn\'t so damn hard to leave ya',
'But every touch is ooh-la-la-la',
'It\'s true la-la-la',
'Ooh, I should be running',
'Ooh, you keep me coming',
'For ya',
'',
'Locked in the hotel',
'There\'s just some things that never change',
'You say, "We\'re just friends."',
'But friends don\'t know the way you taste-la-la-la',
'\'Cause you know it\'s been a long time comin\'',
'Don\'t you let me fall, oh',
'',
'Ooh, when your lips undress me',
'Hooked on your tongue',
'Ooh, love, your kiss is deadly',
'Don\'t stop',
'',
'I love it when you call me Señorita',
'I wish I could pretend I didn\'t need ya',
'But every touch is ooh-la-la-la',
'It\'s true la-la-la',
'Ooh, I should be running',
'Ooh, you know I love it',
'',
'When you call me Señorita',
'I wish it wasn\'t so damn hard to leave ya',
'But every touch is ooh-la-la-la',
'It\'s true la-la-la',
'Ooh, I should be running',
'Ooh, you keep me coming',
'For ya',
'',
'All along I\'ll be coming for ya (for ya)',
'And I hope it meant something to ya',
'Call my name, I\'ll be comin\' for ya (comin\' for ya)',
'Comin\' for ya (comin\' for ya)',
'',
'For ya, for ya (oh, she loves it when I call her), for ya',
'Ooh, I should be running',
'Ooh, you keep me coming',
'For ya'
        ],
    },
    {
        id: 10,
        name: "YourEyes",
        artist: "Barney Sku,Taqiya Zaman",
        src: "YourEyes",
        lyric: [
            'I don\'t believe in soulmates, but',
'Teri nazaron ne dil ka kiya jo',
'Hashar, asar ye hua',
'Ab inamen hee doob ke ho jaanoon',
'Paar, yahi hai dua',
'Teri nazaron ne dil',
'Yeah, your eyes got my heart falling for you',
'You\'re messing with my heart and I still wanna love you',
'I wanna spend my life drowning in your eyes',
'It\'s my only prayer',
'Your eyes got my heart falling for you',
'You\'re messing with my heart and I still wanna love you',
'I wanna spend my life drowning in your eyes',
'It\'s my only prayer, yeah',
'Kaise battaen kyun tujko chaahein',
'Yaaraa, bataa naa paaen',
'Baathen dilon kee dekho Jo baaqee',
'Aankhen tuje samajhaayen',
'Too jaane',
'I don\'t know how to tell you',
'How much I really want you',
'Want you, you, oh oh oh oh',
'So let me come and tell you',
'My feelings that are unsaid',
'Tu jaane naa, Tu jaane naa',
'Tu jaane naa, Tu jaane naa',
'Tu jaane naa, tu jaane naa',
'Tu jaane naa, tu jaane naa'
        ],
    },
    {
        id: 11,
        name: "blue",
        artist: "yung kai",
        src: "blue",
        lyric: [
           'Your morning eyes, I could stare like watching stars',
'I could walk you by, and I\'ll tell without a thought',
'You\'d be mine, would you mind if I took your hand tonight?',
'Know you\'re all that I want this life',
'',
'I\'ll imagine we fell in love',
'I\'ll nap under moonlight skies with you',
'I think I\'ll picture us, you with the waves',
'The oceans colors on your face',
'I\'ll leave my heart with your air',
'So let me fly with you',
'Will you be forever with me?',
'',
'My love will always stay by you',
'I\'ll keep it safe so don\'t you worry a thing, I\'ll tell you I love you more',
'It\'s stuck with you forever so promise you won\'t let it go',
'I\'ll trust the universe will always bring me to you',
'',
'I\'ll imagine we fell in love',
'I\'ll nap under moonlight skies with you',
'I think I\'ll picture us, you with the waves',
'The oceans colors on your face',
'I\'ll leave my heart with your air',
'So let me fly with you',
'Will you be forever with me?'
        ],
    },
    {
        id: 12,
        name: "Espresso",
        artist: "Sabrina Carpenter",
        src: "Espresso",
        lyric: [
          'Now he\'s thinkin\' \'bout me every night, oh',
'Is it that sweet? I guess so',
'Say you can\'t sleep, baby, I know',
'That\'s that me espresso',
'Move it up, down, left, right, oh',
'Switch it up like Nintendo',
'Say you can\'t sleep, baby, I know',
'That\'s that me espresso',
'',
'I can\'t relate',
'To desperation',
'My \'give a fucks\' are on vacation',
'And I got this one boy',
'And he won\'t stop calling',
'When they act this way',
'I know I got em\'',
'',
'Too bad your ex don\'t do it for ya',
'Walked in and dream came trued it for ya',
'Soft skin and I perfumed it for ya',
'I know I Mountain Dew it for ya',
'That morning coffee brewed it for ya',
'One touch and I brand newed it for ya',
'',
'Now he\'s thinkin\' \'bout me every night, oh',
'Is it that sweet? I guess so',
'Say you can\'t sleep, baby, I know',
'That\'s that me espresso',
'Move it up, down, left, right, oh',
'Switch it up like Nintendo',
'Say you can\'t sleep, baby, I know',
'That\'s that me espresso',
'',
'Holy shit',
'Is it that sweet? I guess so',
'',
'I\'m working late \'cause I\'m a singer',
'Oh, he looks so cute wrapped around my finger',
'My twisted humor make him laugh so often',
'My honey bee, come and get this pollen',
'',
'Too bad your ex don\'t do it for ya',
'Walked in and dream came trued it for ya',
'Soft skin and I perfumed it for ya',
'I know I Mountain Dew it for ya',
'That morning coffee brewed it for ya',
'One touch and I brand newed it for ya',
'',
'Now he\'s thinkin\' \'bout me every night, oh',
'Is it that sweet? I guess so',
'Say you can\'t sleep, baby, I know',
'That\'s that me espresso',
'Move it up, down, left, right, oh',
'Switch it up like Nintendo',
'Say you can\'t sleep, baby, I know',
'That\'s that me espresso',
'',
'Thinkin\' \'bout me every night, oh',
'Is it that sweet? I guess so',
'Say you can\'t sleep, baby, I know',
'That\'s that me espresso',
'Move it up, down, left, right, oh',
'Switch it up like Nintendo',
'Say you can\'t sleep, baby, I know',
'That\'s that me espresso',
'',
'Is it that sweet? I guess so',
'Mmm, that\'s that me espresso'
        ],
    },
    {
        id: 13,
        name: "Die With A Smile",
        artist: "Lady Gaga & Bruno Mars",
        src: "diesmile",
        lyric: [
       'I, I just woke up from a dream',
'Where you and I had to say goodbye',
'And I don\'t know what it all means',
'But since I survived, I realized',
'',
'Wherever you go, that\'s where I\'ll follow',
'Nobody\'s promised tomorrow',
'So I\'ma love you every night like it\'s the last night',
'Like it\'s the last night',
'',
'If the world was ending',
'I\'d wanna be next to you',
'If the party was over',
'And our time on Earth was through',
'I\'d wanna hold you just for a while',
'And die with a smile',
'If the world was ending',
'I\'d wanna be next to you',
'',
'(Ooh, ooh)',
'',
'Ooh, lost, lost in the words that we scream',
'I don\'t even wanna do this anymore',
'\'Cause you already know what you mean to me',
'And our love\'s the only war worth fighting for',
'',
'Wherever you go, that\'s where I\'ll follow',
'Nobody\'s promised tomorrow',
'So I\'ma love you every night like it\'s the last night',
'Like it\'s the last night',
'',
'If the world was ending',
'I\'d wanna be next to you',
'If the party was over',
'And our time on Earth was through',
'I\'d wanna hold you just for a while',
'And die with a smile',
'If the world was ending',
'I\'d wanna be next to you',
'',
'Right next to you',
'Next to you',
'Right next to you',
'Oh-oh',
'',
'If the world was ending',
'I\'d wanna be next to you',
'If the party was over',
'And our time on Earth was through',
'I\'d wanna hold you just for a while',
'And die with a smile',
'If the world was ending',
'I\'d wanna be next to you',
'If the world was ending',
'I\'d wanna be next to you',
'',
'(Ooh, ooh)',
'I\'d wanna be next to you'
        ],
    },
    {
        id: 14,
        name: "Hymn For The Weekend",
        artist: "Coldplay",
        src: "Coldplay",
        lyric: [
    'Drink from me, drink from me',
'That I shoot across the sky',
'Symphony',
'That I shoot across the sky',
'We\'re on a...',
'Drink from me, drink from me',
'That I shoot across the sky',
'Symphony',
'(So high, so high)',
'That I shoot across the sky',
'',
'Oh, angel sent from up above',
'You know you make my world light up',
'When I was down, when I was hurt',
'You came to lift me up',
'Life is a drink, and love\'s a drug',
'Oh, now I think I must be miles up',
'When I was a river, dried up',
'You came to rain a flood',
'',
'You said drink from me, drink from me',
'When I was so thirsty',
'Poured on a symphony',
'Now I just can\'t get enough',
'Put your wings on me, wings on me',
'When I was so heavy',
'Poured on a symphony',
'When I\'m low, low, low, low',
'',
'I, oh, I, oh, I',
'Got me feeling drunk and high',
'So high, so high',
'Oh, I, oh, I, oh, I',
'Now I\'m feeling drunk and high',
'So high, so high',
'Woo!',
'',
'Oh, angel sent from up above',
'I feel it coursing through my blood',
'Life is a drink, your love\'s about',
'To make the stars come out',
'',
'Put your wings on me, wings on me',
'When I was so heavy',
'Poured on a symphony',
'When I\'m low, low, low, low',
'',
'I, oh, I, oh, I',
'Got me feeling drunk and high',
'So high, so high',
'Oh I, oh, I, oh, I',
'Now I\'m feeling drunk and high',
'So high, so high',
'',
'I, oh, I, oh, I',
'La la la la la la la',
'So high, so high',
'I, oh, I, oh, I',
'I\'m feeling drunk and high',
'So high, so high',
'',
'That I shoot across the sky',
'That I shoot across the...',
'That I shoot across the sky',
'Watch me shoot across the..',
'That I shoot across the sky',
'That I shoot across the...',
'That I shoot across the sky',
'That I shoot across the...'
        ],
    },
    {
        id: 15,
        name: "Attention",
        artist: "Charlie Puth",
        src: "Attention",
        lyric: [
           'You\'ve been runnin\' \'round, runnin\' \'round, runnin\' \'round throwin\' that dirt all on my name',
'\'Cause you knew that I, knew that I, knew that I\'d call you up',
'You\'ve been going \'round, going \'round, going \'round every party in LA',
'\'Cause you knew that I, knew that I, knew that I\'d be at one, oh',
'',
'I know that dress is karma, perfume regret',
'You got me thinking \'bout when you were mine, oh',
'And now I\'m all up on ya, what you expect?',
'But you\'re not coming home with me tonight',
'',
'You just want attention',
'You don\'t want my heart',
'Maybe you just hate the thought of me with someone new',
'Yeah, you just want attention',
'I knew from the start',
'You\'re just making sure I\'m never gettin\' over you, oh',
'',
'You\'ve been runnin\' round, runnin\' round, runnin\' round throwing that dirt all on my name',
'\'Cause you knew that I, knew that I, knew that I\'d call you up',
'Baby, now that we\'re, now that we\'re, now that we\'re right here standing face to face',
'You already know, \'ready know, \'ready know that you won, oh',
'',
'I know that dress is karma (dress is karma), perfume regret, yeah',
'You got me thinking \'bout when you were mine, oh',
'(You got me thinking \'bout when you were mine)',
'And now I\'m all up on ya (all up on ya), what you expect?',
'(Oh, baby)',
'But you\'re not coming home with me tonight, oh no',
'',
'You just want attention',
'You don\'t want my heart',
'Maybe you just hate the thought of me with someone new, someone new',
'Yeah, you just want attention, oh',
'I knew from the start, the start',
'You\'re just making sure I\'m never gettin\' over you, over you, oh',
'',
'What are you doin\' to me?',
'What are you doin\', huh? (What are you doin\'?)',
'What are you doin\' to me?',
'What are you doin\', huh? (What are you doin\'?)',
'What are you doin\' to me?',
'What are you doin\', huh? (What are you doin\'?)',
'What are you doin\' to me?',
'What are you doin\', huh?',
'',
'I know that dress is karma, perfume regret',
'You got me thinking \'bout when you were mine',
'And now I\'m all up on ya, what you expect?',
'But you\'re not coming home with me tonight',
'',
'You just want attention',
'You don\'t want my heart',
'Maybe you just hate the thought of me with someone new',
'Yeah, you just want attention',
'I knew from the start',
'You\'re just making sure I\'m never gettin\' over you, over you',
'',
'What are you doin\' to me? (hey)',
'What are you doin\', huh? (what are you doin\', what?)',
'What are you doin\' to me?',
'What are you doin\', huh? (yeah, you just want attention)',
'What are you doin\' to me? (I knew from the start)',
'What are you doin\', huh?',
'(You\'re just making sure I\'m never gettin\' over you)',
'What are you doin\' to me?',
'What are you doin\', huh?'
        ]
    },
    {
        id: 16,
        name: " We Don't Talk Anymore (feat. Selena Gomez)",
        artist: "Charlie Puth & Selena Gomez",
        src: "talk",
        lyric: [
            'We don\'t talk anymore',
'We don\'t talk anymore',
'We don\'t talk anymore',
'Like we used to do',
'We don\'t love anymore',
'What was all of it for?',
'Oh, we don\'t talk anymore',
'Like we used to do',
'I just heard you found the one you\'ve been looking',
'You\'ve been looking for',
'I wish I would have known that wasn\'t me',
'Cause even after all this time I still wonder',
'Why I can\'t move on',
'Just the way you did so easily',
'Don\'t wanna know',
'What kind of dress you\'re wearing tonight',
'If he\'s holding onto you so tight',
'The way I did before',
'I overdosed',
'Should\'ve known your love was a game',
'Now I can\'t get you out of my brain',
'Oh, it\'s such a shame',
'That we don\'t talk anymore',
'We don\'t talk anymore',
'We don\'t talk anymore',
'Like we used to do',
'We don\'t love anymore',
'What was all of it for?',
'Oh, we don\'t talk anymore',
'Like we used to do',
'I just hope you\'re lying next to somebody',
'Who knows how to love you like me',
'There must be a good reason that you\'re gone',
'Every now and then I think you',
'Might want me to come show up at your door',
'But I\'m just too afraid that I\'ll be wrong',
'Don\'t wanna know',
'If you\'re looking into her eyes',
'If she\'s holding onto you so tight',
'The way I did before',
'I overdosed',
'Should\'ve known your love was a game',
'Now I can\'t get you out of my brain',
'Oh, it\'s such a shame',
'That we don\'t talk anymore',
'We don\'t talk anymore',
'We don\'t talk anymore',
'Like we used to do',
'We don\'t love anymore',
'What was all of it for?',
'Oh, we don\'t talk anymore',
'Like we used to do',
'Don\'t wanna know',
'What kind of dress you\'re wearing tonight',
'If he\'s holding onto you so tight',
'The way I did before',
'I overdosed',
'Should\'ve known your love was a game',
'Now I can\'t get you out of my brain',
'Oh, it\'s such a shame',
'That we don\'t talk anymore',
'We don\'t talk anymore',
'We don\'t talk anymore',
'Like we used to do',
'We don\'t love anymore',
'What was all of it for?',
'Oh, we don\'t talk anymore',
'Like we used to do',
'We don\'t talk anymore',
'Don\'t wanna know',
'What kind of dress you\'re wearing tonight',
'If he\'s giving it to you just right',
'The way I did before',
'We don\'t talk anymore',
'We don\'t talk anymore',
'We don\'t talk anymore',
'Like we used to do',
'We don\'t love anymore',
'What was all of it for?',
'Oh, we don\'t talk anymore',
'Like we used to do',
        ],
    },
];
